# Generated by Django 3.2.7 on 2021-11-02 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='answered',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
